sudo: required

language: javascript

branches:
    only:
        - master
        - debian
        - 7.0-alpine
        - 7.0-debian

notifications:
    slack:
        secure: tgQIiODFrpQ3pUCMTCPfmG+UmI+G04uMplkeomH6qKAPvfB003lf4Dt6Z0Fr0khdAxNa+bbOmaKCF3BLyJ6gcWT9fZAYeXyz0Dk3tzEjhihWwDxoRUJRoY5XldoHyeWo4fXw3tfQE6DWZ9ixyfWKMNaCx7At6cwMl/AMgDrQfm2UDS/MxYiWMMDW920vABDV9DSfsvrkC+6tcHYCOnjwS27R9Z0rDfeykJ2zKBDdgh7Em1/TX8z/pr1FJk1oVrVjOrUoNu729Jn/PfVkMSAAuWwpIk6iMzBr6dVuj6qVlYENMiwBJJ+7J5ERrCxbi6JbKJf8WRhc36nVHzz/X9onHaTzgBCDNAHtWWjm15Krb0HXeSkLcXi+GEsllJDCAVriwRpGAre/QUZHzIk2jCQUfOiiVrsyE2yJjPMJ3Zpa23oYKWA8nh/51BQoa9lL3TgZFUxqqtK2RU4ZSMDDdiLhQr5LhFPlMzPIKfYvV3Cqdg74jcq9WnWq4DFyCCfh7Kd5g5P6tAEV10wx+XHkfbczgd/KWFs7S8mo8qE7b7sAnJpgDH3B//4h2TVzZRw1BWrysdzH0O4uTBVfr3Lh0SiRschAW5uNBSHBaEN/N7IBuDNoMMPEiqoLeYLVnIVqHOvBVWkxkU6HxE/iW412Xf2CDTrQyWIlaSlnIphf4bZf8y0=

services:
    - docker

before_install:

script:
    # Test the build itself
    - docker build -t mkenney/npm:ci-build .

    # Test the built image
    - cd test
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/bower install
    - ls bower_components
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/npm install
    - ls node_modules
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/grunt
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/gulp
    - rm -rf node_modules
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/yarn install
    - ls node_modules
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/grunt
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/gulp
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/generate-md --input ./md --output ./html
    - ls html/index.html

    # Test the installation script and wrapper scripts
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s bower ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s generate-md ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s grunt ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s gulp ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s node ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s npm ${BRANCH/master/latest} .
    - curl -L https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh | sh -s yarn ${BRANCH/master/latest} .
    - rm -rf bower_components
    - rm -rf node_modules
    - ./bower install
    - ls bower_components
    - ./npm install
    - ls node_modules
    - ./grunt
    - ./gulp
    - rm -rf node_modules
    - ./yarn install
    - ls node_modules
    - ./grunt
    - ./gulp
    - ./generate-md --input ./md --output ./html
    - ls html/index.html

    # Output versions
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/bower --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/generate-md --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/grunt --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/gulp --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/node --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/npm --version
    - docker run --rm -t -i -v $(pwd):/src:rw mkenney/npm:ci-build /run-as-user /usr/local/bin/yarn --version

after_success:
    - cd ../ci
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh ./deploy.sh; fi
